# Generated by Django 3.2.8 on 2021-12-08 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_nick', models.TextField(max_length=45)),
                ('adm_passw', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullNameCity', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='priceo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=11)),
                ('mailo', models.TextField(max_length=45)),
                ('passwordo', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullStreet', models.TextField(max_length=45)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forKurs2.city')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanityPlaces', models.IntegerField(max_length=3)),
                ('Street_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forKurs2.street')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField(default=datetime.datetime(2021, 12, 8, 11, 59, 39, 530318))),
                ('timeStart', models.TimeField(default=datetime.datetime(2021, 12, 8, 11, 59, 39, 530318))),
                ('occupiedPlace', models.IntegerField(max_length=3)),
                ('statuso', models.BooleanField()),
                ('Parking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forKurs2.parking')),
                ('usero_idusero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forKurs2.usero')),
            ],
        ),
    ]
