# Generated by Django 3.2.8 on 2021-12-08 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forKurs2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dateStart',
        ),
        migrations.AlterField(
            model_name='orders',
            name='timeStart',
            field=models.TextField(auto_created=datetime.datetime(2021, 12, 8, 12, 2, 6, 595439)),
        ),
    ]
