# Generated by Django 3.2.8 on 2021-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forKurs2', '0004_alter_orders_timestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='timeStart',
            field=models.TextField(),
        ),
    ]
